import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import '../../styles/global.css';
import Header from './components/common/Header';
import Footer from './components/common/Footer';
import Buttom from './components/common/Buttom';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body >
        <Header/>
        {children}
        <Footer/>
        <Buttom/>
      </body>
    </html>
  );
}
